### ISSUE TITLE
Directory does not contain app.yaml or app.yml

### ISSUE THREAD

**Issue by kplaube** [nasa/apod-api#2]
I've followed all the steps in README, from setup to running the project. But when I try to run it through `dev_appserver.py .`, it raises the following exception:

>google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "." is a directory but does not contain app.yaml or app.yml

I couldn't find this file inside the project (sorry, I'm not so experienced in GAE). Should I create my own `app.yml` file? Or is something missing?

**Comment by RaihanStark** [comment]
yeah me too

**Comment by umashankarpandey** [comment]
Just do the bellow steps 
git clone -b phase0-helloworld https://github.com/GoogleCloudPlatform/appengine-php-guestbook.git helloworld

cd helloworld

dev_appserver.py --php_executable_path=/usr/bin/php-cgi $PWD

Now it is working 

Thanks and let me know issues

**Comment by evantayloryates** [comment]
@umashankarpandey will you explain what your solution is doing? Running it as is does not solve the problem from what I can tell

**Comment by coralieco** [comment]
I've got the same issue here. Did any body find a solution ?

I added a file `app.yaml`  in the project with these lines only:
```
runtime: python27
api_version: 1
threadsafe: true
```
following the [Google App Engine documentation](https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_element).

It does definitely help to run the server.
```
➜  apod-api git:(master) ✗ dev_appserver.py .

INFO     2018-12-24 12:46:58,686 devappserver2.py:278] Skipping SDK update check.
INFO     2018-12-24 12:46:58,761 api_server.py:275] Starting API server at: http://localhost:58850
INFO     2018-12-24 12:46:58,764 dispatcher.py:256] Starting module "default" running at: http://localhost:8080
INFO     2018-12-24 12:46:58,766 admin_server.py:150] Starting admin server at: http://localhost:8000
...
```

But there are missing handlers in the app.yaml file. As I have this message:
```
The url "/" does not match any handlers.
```
when visiting `http://localhost:8080/`

I have no clue what we are supposed to use as handlers to make it work. 

Thanks !

**Comment by under-score** [comment]
me too
`The url "/" does not match any handlers.`

**Comment by nullx5** [comment]
> yaml file for GuestBook  Python
---
```
application: app_guestbook
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: guestbook.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

```
![https://i.imgur.com/kN2VMVc.png](https://i.imgur.com/kN2VMVc.png)
